{
  "type": "record",
  "name": "flags_logs_exo2phorp",
  "namespace": "org.neonscience.schema.dp0p",
  "doc": "Log data flags for exo2phorp sensor",
  "fields": [
    {
      "name": "readout_time",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "Timestamp of readout expressed in milliseconds since epoch"
    },
    {
      "name": "pHLogDataQF",
      "type": [
        "null",
        "int"
        ],
      "default": null,
      "doc": "Quality flag for pH log data (1=fail, 0=pass, -1=NA (i.e., could not be run))",
      "__neon_units": "NA"
    }
    ]
}
