{
    "type": "record",
    "name": "exo2turbidity_log_data",
    "namespace": "org.neonscience.schema.device",
    "doc": "YSI EXO Turbidity Smart Sensor Log Data",
    "__version": "1.0",
    "__neon_parts": [
        "0320170028"
    ],
    "fields": [
        {
            "name": "source_id",
            "type": "string",
            "doc": "Source serial number or MAC address"
        },
        {
            "name": "site_id",
            "type": "string",
            "doc": "NEON site identifier"
        },
        {
            "name": "readout_time",
            "type": {
                "type": "long",
                "logicalType": "timestamp-millis"
            },
            "doc": "Timestamp of readout expressed in milliseconds since epoch",
            "__neon_units": "millisecond"
        },
        {
            "name": "turbidity",
            "type": [
                "null",
                "float"
            ],
            "default": null,
            "doc": "Turbidity of water as FNU",
            "__neon_units": "formazinNephelometricUnit",
            "__neon_stream_id": "30"
        }
    ]
}