{
  "type": "record",
  "name": "windBuoy_quality_metrics",
  "namespace": "org.neonscience.schema.dp01",
  "doc": "Buoy wind quality metrics",
  "__version": "1.0",
  "fields": [
    {
      "name": "startDateTime",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "Date and time at which a sampling is initiated (inclusive)"
    },
    {
      "name": "endDateTime",
      "type": {
        "type": "long",
        "logicalType": "timestamp-millis"
      },
      "doc": "Date and time at which a sampling is completed (exclusive)"
    },    
    {
      "name": "buoyWindDirDeadZonePassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the passed outcomes of the dead band test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirDeadZoneFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the failed outcomes of the dead band test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirDeadZoneNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes when the dead band test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirCalmWindPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the passed outcomes of the calm wind test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirCalmWindFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the failed outcomes of the calm wind test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirCalmWindNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "	Buoy wind direction quality metric that summarizes when the calm wind test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedValidCalPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the passed outcomes of the valid calibration check over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedValidCalFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the failed outcomes of the valid calibration check over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedValidCalNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes when the valid calibration check could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirValidCalPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the passed outcomes of the valid calibration check over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirValidCalFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the failed outcomes of the valid calibration check over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirValidCalNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes when the valid calibration check could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedSuspectCalPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the passed outcomes of the suspect calibration check over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedSuspectCalFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the failed outcomes of the suspect calibration check over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedSuspectCalNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes when the suspect calibration check could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirSuspectCalPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the passed outcomes of the suspect calibration check over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirSuspectCalFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the failed outcomes of the suspect calibration check over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirSuspectCalNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes when the suspect calibration check could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedNullPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the passed outcomes of the null test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedNullFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the failed outcomes of the null test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedNullNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes when the null test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedGapPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the passed outcomes of the gap test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedGapFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the failed outcomes of the gap test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedGapNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes when the gap test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedRangePassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the passed outcomes of the range test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedRangeFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the failed outcomes of the range test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedRangeNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes when the range test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedPersistencePassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the passed outcomes of the persistence test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedPersistenceFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes the failed outcomes of the persistence test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedPersistenceNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric that summarizes when the persistence test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirNullPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the passed outcomes of the null test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirNullFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the failed outcomes of the null test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirNullNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes when the null test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirGapPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the passed outcomes of the gap test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirGapFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the failed outcomes of the gap test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirGapNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes when the gap test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirRangePassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the passed outcomes of the range test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirRangeFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the failed outcomes of the range test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirRangeNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes when the range test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirPersistencePassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the passed outcomes of the persistence test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirPersistenceFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes the failed outcomes of the persistence test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirPersistenceNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric that summarizes when the persistence test could not be run over the averaging period, as a percent	percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompNullPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes the passed outcomes of the null test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompNullFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes the failed outcomes of the null test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompNullNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes when the null test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompGapPassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes the passed outcomes of the gap test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompGapFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes the failed outcomes of the gap test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompGapNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes when the gap test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompRangePassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes the passed outcomes of the range test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompRangeFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes the failed outcomes of the range test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompRangeNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes when the range test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompPersistencePassQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes the passed outcomes of the persistence test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompPersistenceFailQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes the failed outcomes of the persistence test over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyCompPersistenceNAQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy compass quality metric that summarizes when the persistence test could not be run over the averaging period, as a percent",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedAlphaQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric detailing the outcomes of the alpha quality flag over the averaging period, as a percent and detailed in NEON.DOC.001113",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedBetaQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind speed quality metric detailing the outcomes of the beta quality flag over the averaging period, as a percent and detailed in NEON.DOC.001113",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindSpeedFinalQF",
      "type": [
        "null",
        "int8"
        ],
      "default": null,
      "doc": "Buoy wind speed quality flag indicating whether a data product has passed or failed an overall assessment of its quality, detailed in NEON.DOC.001113 (1=fail, 0=pass)",
      "__neon_units": "NA"
    },
    {
      "name": "buoyWindDirAlphaQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric detailing the outcomes of the alpha quality flag over the averaging period, as a percent and detailed in NEON.DOC.001113",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirBetaQM",
      "type": [
        "null",
        "float"
        ],
      "default": null,
      "doc": "Buoy wind direction quality metric detailing the outcomes of the beta quality flag over the averaging period, as a percent and detailed in NEON.DOC.001113",
      "__neon_units": "percent"
    },
    {
      "name": "buoyWindDirFinalQF",
      "type": [
        "null",
        "int8"
        ],
      "default": null,
      "doc": "Buoy wind direction quality flag indicating whether a data product has passed or failed an overall assessment of its quality, detailed in NEON.DOC.001113 (1=fail, 0=pass)",
      "__neon_units": "NA"
    }
  ]
}
