name: CERT-parQuantumLine-avro-schemas
on:
  push:
    branches:
      - 'cert'
    paths:
      - 'avro_schemas/parQuantumLine/**'
  workflow_dispatch: {} # Allows trigger of workflow from web interface
jobs:
  put-file:
    runs-on: arc-neon-gke
    #runs-on: ubuntu-latest 
    env:
      PACHD_ADDRESS: grpcs://pachyderm-cert.transitions-nonprod.gcp.neoninternal.org:443
      PACH_TOKEN: ${{ secrets.RepoOwnerPachydermCert }}
      REPO: parQuantumLine_avro_schemas # Pachyderm repo
      BRANCH: master 
      IN_PATH: 'avro_schemas/parQuantumLine' # Single path to local file or directory. If directory, all files in directory will be place in pachyderm at OUT_PATH. 
      OUT_PATH: '/parQuantumLine' # Path to place the file(s) in Pachyderm. If IN_PATH is a file, specify to the file. If IN_PATH is a directory, specify to the directory. 
    steps:
      - uses: actions/checkout@v4
      - run: ls -la
      
      - uses: actions/setup-python@v3
        with:
          python-version: '3.10' # Version range or exact version of a Python version to use, using SemVer's version range syntax
          cache: 'pip'
      - run: pip install -r .github/workflow_scripts/put_files/requirements.txt
      - run: python3 -u .github/workflow_scripts/put_files/put_files.py
